#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

#Prompt color
export PS1="\[\e[1;33m\][\[\e[m\]\[\e[31m\]\u\[\e[m\]\[\e[1;33m\]@\[\e[m\]\[\e[32m\]\h\[\e[m\]:\[\e[1;33m\]\w\[\e[m\]\[\e[1;33m\]]\[\e[m\]\[\e[1;33m\]\\$→\[\e[m\] "
